FORMAT: 1A
HOST: http://notification.zazoapp.com

# Zazo Notification

## Authentication

The default mehtod is **HTTP Digest** with service's `username` and `password`.

The **HTTP Basic** works only for `development` environment (as in examples).

When *unauthorized* response will be as for [Settings](#application-settings-get).

## Group Application

### Status [GET /api/v1/status]

API status: `app_name`, `version` and `authentication_method`.
Authentication not required.

+ Request (application/json)

+ Response 200 (application/json; charset=utf-8)

        {
            "app_name": "Zazo Notification",
            "version": "0.1.0",
            "authentication_method": "basic"
        }

### Settings [GET /api/v1/settings]

+ Request Success (application/json)

    + Headers

            Authorization: Basic bm90aWZpY2F0aW9uOl05MkQ4Zlc0OTcuRjY0S3tNK3g5b1A5Sg==


+ Response 200 (application/json; charset=utf-8)

        {
            "app_name": "Zazo Notification",
            "version": "0.1.0",
            "authentication_method": "basic",
            "stub_mobile_number": false
        }

+ Request Unauthorized (application/json)

+ Response 401 (application/json; charset=utf-8)

        {
            "status": "unauthorized"
        }

## Group Notifications

### Index [GET /api/v1/notifications]

List of available notifications

+ Request (application/json)

    + Headers

            Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

+ Response 200 (application/json; charset=utf-8)


        {
            "data": [
                {
                    "name": "email",
                    "description": "Notification via Email over AWS",
                    "required_params": [
                        "to",
                        "subject",
                        "body"
                    ]
                },
                {
                    "name": "sms",
                    "description": "SMS notification via Twilio",
                    "required_params": [
                        "mobile_number",
                        "body"
                    ]
                }
            ],
            "meta": {
                "total": 2
            }
        }

### Unkonwn [POST /api/v1/notifications/unknown]

+ Request (application/json)

    + Headers

            Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

+ Response 404 (application/json; charset=utf-8)

        {
            "status": "not_found",
            "errors": {
                "Notification::UnknownNotification": "Notification \"unknown\" not found"
            }
        }

### SMS [POST /api/v1/notifications/sms]

Send SMS via Twilio service.

+ Parameters
    + mobile_number: +380939523746 (string) - Destination mobile number
    + body: Hello from Zazo! (string) - SMS body
    + from: +16502453537 (string, optional) - Override from number
        + Default: +16503766005


+ Request Success (application/json)

    + Headers

            Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

    + Body

            {
                "mobile_number": "+380939523746",
                "body": "Hello from Zazo!"
            }

+ Response 200 (application/json; charset=utf-8)

        {
            "status": "success",
            "original_response: {
                "sid": "SM272eb583ba9f40859abd816e97958bbf",
                "date_created": "Thu, 19 Mar 2015 22:52:19 +0000",
                "date_updated": "Thu, 19 Mar 2015 22:52:19 +0000",
                "date_sent": null,
                "account_sid": "twilio_sid",
                "to": "+380939523746",
                "from": "+16503766005",
                "body": "Zazo access code: 623030",
                "status": "queued",
                "num_segments": "1",
                "num_media": "0",
                "direction": "outbound-api",
                "api_version": "2010-04-01",
                "price": null,
                "price_unit": "USD",
                "error_code": null,
                "error_message": null,
                "uri": "/2010-04-01/Accounts/twilio_ssid/Messages/SM272eb583ba9f40859abd816e97958bbf.json",
                "subresource_uris": {
                    "media": "/2010-04-01/Accounts/twilio_ssid/Messages/SM272eb583ba9f40859abd816e97958bbf/Media.json"
                }
           }
        }

+ Request Invalid parameters (application/json)

    + Headers

            Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

    + Body

            {
                "mobile_number": "+380939523746"
            }

+ Response 422 (application/json; charset=utf-8)

        {
            "status": "invalid",
            "errors": {
                "body": [
                    "can't be blank"
                ]
            },
            "original_response": null
        }

+ Request Invalid mobile_number (application/json)

    + Headers

            Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

    + Body

            {"mobile_number":"+20227368296","body":"Hello from Zazo!"}

+ Response 400 (application/json; charset=utf-8)

        {
            "status": "failure",
            "errors": {
                "Twilio::REST::RequestError": [
                    "'To' number is not a valid mobile number"
                ]
            },
            "original_response": [
                {
                  "code": 21614,
                  "message": "'To' number is not a valid mobile number",
                  "more_info": "https://www.twilio.com/docs/errors/21614",
                  "status": 400
                }
            ]
        }

### Email [POST /api/v1/notifications/email]

Notification via Email over AWS

+ Parameters
    + to: Alex Ulianytskyi <a.ulyanitsky@gmail.com> (string) - Recipient's address.
    + subject: Zazo Notification (string) - Subject of mail.
    + body: Hello from Zazo! (string) - Mail body as HTML or plain text.
    + from: Zazo <support@zazoapp.com> (string, optional) - Sender's address.
        + Default: Sani Elfishawy <elfishawy.sani@gmail.com>
    + content_type: `text/html; charset=utf-8` (string, optional) - Message *Content-Type* header.
        + Default: `text/html; charset=utf-8`

+ Request Success (application/json)

    + Headers

            Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

    + Body

            {
                "to": "Alex Ulianytskyi <a.ulyanitsky@gmail.com>",
                "subject": "Zazo Notification",
                "body":"Hello from Zazo!"
            }

+ Response 200 (application/json; charset=utf-8)

        {
            "status": "success",
            "original_response": null
        }

+ Request Parameter `to` is missing (application/json)

    + Headers

            Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

    + Body

            {
                "subject": "Zazo Notification",
                "body":"Hello from Zazo!"
            }

+ Response 422 (application/json; charset=utf-8)

        {
            "status": "invalid",
            "errors": {
                "to": [
                    "can't be blank"
                ]
            },
            "original_response": null
        }

+ Request Invalid `to` parameter (application/json)

    + Headers

            Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

    + Body

            {
                "subject": "Zazo Notification",
                "body": "Hello from Zazo!",
                "to": "test@example"
            }

+ Response 422 (application/json; charset=utf-8)

        {
            "status": "invalid",
            "errors": {
                "to": [
                    "is invalid"
                ]
            },
            "original_response": null
        }

+ Request Invalid Content Type (application/json)

    + Headers

            Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

    + Body

            {
                "subject": "Zazo Notification",
                "body": "<h1>Hi there!</h1><p>This is test mail from Zazo.</p>",
                "to": "Alex Ulianytsky <a.ulyanitsky@gmail.com>",
                "content_type":"foo/unknown"
            }

+ Response 422 (application/json; charset=utf-8)

        {
            "status": "invalid",
            "errors": {
                "content_type": [
                    "is not valid MIME type"
                ]
            },
            "original_response": null
        }

+ Request Failure (application/json)

    + Headers

            Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

    + Body

            {
                "to": "Alex Ulianytsky <a.ulyanitsky@gmail.com>",
                "subject": "Zazo Notification",
                "body": "Hello from Zazo!",
                "from": "Zazo Support <support@zazoapp.com>"
            }

+ Response 400 (application/json; charset=utf-8)

        {
            "status": "failure",
            "errors": {
                "Net::SMTPFatalError": [
                    "554 Message rejected: Email address is not verified.\n"
                ]
            },
            "original_response": null
        }

### Mobile [POST /api/v1/notifications/mobile]

Mobile notification for iOS or Android

+ Parameters
    + subject: Zazo Notification (string) - Subject of notification.
    + device_platform: ios (string) - Devise platform: iOS or Android.
    + device_token: xxxxxxxxxxxx (string) - Token to send notification.
    + device_build: prod (string, optional) - iOS device build: dev or prod .
    + payload: { type: 'friend_joined' } (hash) - Additonal data, type is required.

+ Request Success (application/json)

    + Headers

            Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

    + Body

            {
                "subject": "Zazo Notification",
                "device_platform": "android",
                "device_token": "xxxxxxxxxxxx",
                "payload": {
                    "type": "friend_joined",
                    "content": "Friend Joined!"
                }
            }

+ Response 200 (application/json; charset=utf-8)

        {
            "status": "success",
            "original_response": {
                "multicast_id": 6548991881139788460,
                "success": 1,
                "failure": 0,
                "canonical_ids": 0,
                "results": [{
                    "message_id": "0:1428003070211543%7c7dc9e1f9fd7ecd"
                }]
            }
        }

+ Request Required Parameters are missing (application/json)

    + Headers

            Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

    + Body

            {
                "subject": "Zazo Notification",
                "device_platform": "android"
            }

+ Response 422 (application/json; charset=utf-8)

        {
            "status": "invalid",
            "errors": {
                "device_token": [
                    "can't be blank"
                ],
                "payload": [
                    "can't be blank"
                ]
            },
            "original_response": null
        }

+ Request Failure (application/json)

    + Headers

            Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

    + Body

            {
                "subject": "Zazo Notification",
                "device_platform": "android",
                "device_token": "xxxxxxxxxxxx",
                "payload": {
                    "type": "friend_joined",
                    "content": "Friend Joined!"
                }
            }

+ Response 400 (application/json; charset=utf-8)

        {
            "status": "failure",
            "errors": {
                "response": [
                    "InvalidRegistration"
                ]
            },
            "original_response": {
                "multicast_id": 6548991881139788460,
                "success": 0,
                "failure": 1,
                "canonical_ids": 0,
                "results": [{
                    "message_id": "0:1428003070211543%7c7dc9e1f9fd7ecd"
                }]
            }
        }
