FORMAT: 1A
HOST: http://notification.zazoapp.com

# Zazo Notification

## Authentication

The default mehtod is **HTTP Digest** with service's `username` and `password`.

The **HTTP Basic** will work for _development_ environment (as in examples).

On *unauthorized* response will be:

+ Response 401 (application/json)

    + Body

            {
                "status": "unauthorized"
            }

## Failure

If parameters is invalid:

+ Response 422 (application/json)

    + Body

            {
                "status": "invalid",
                "errors": [
                    {
                      "body": "must be present"
                    }
                ],
                "original_response": null
            }

On backend service error:

+ Response 400 (application/json)

    + Body

            {
                "status": "failure",
                "errors": [
                    {
                      "Twilio error": "'To' number is not a valid mobile number"
                    }
                ],
                "original_response": [
                    {
                      "code": 21614,
                      "message": "'To' number is not a valid mobile number",
                      "more_info": "https://www.twilio.com/docs/errors/21614",
                      "status": 400
                    }
               ]
            }

### List of available notifications [GET /api/v1/notifications]

+ Request
    + Headers
            Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

+ Response 200 (application/json; charset=utf-8)


        {
            "status": "success",
            "data": [
                {
                    "name": "sms",
                    "description": "SMS notification via Twilio",
                    "required_params": ["mobile_number", "body"]
                }
            ],
            "meta": {
                "total": 1
            }
        }


### SMS [POST /api/v1/notifications/sms]

Send SMS via Twilio service.

+ Parameters
    + mobile_number: +380939523746 (string) - Destination mobile number
    + body: Hello from Zazo! (string) - SMS body
    + from: +16502453537 (string, optional) - Override from number
        + Default: +16503766005

+ Request (application/json)
    + Headers

        Authorization: Basic cmVub3RpZmljYXRpb246dThyZCZkNFkzTjQyOXpXMyRRKD1YOGJL

    + Body

            {
                "mobile_number": "+380939523746",
                "body": "Hello from Zazo!"
            }

+ Response 200 (application/json)

    + Body

            {
                "status": "success",
                "original_response: {
                    "sid": "SM272eb583ba9f40859abd816e97958bbf",
                    "date_created": "Thu, 19 Mar 2015 22:52:19 +0000",
                    "date_updated": "Thu, 19 Mar 2015 22:52:19 +0000",
                    "date_sent": null,
                    "account_sid": "<twilio_sid>",
                    "to": "+380939523746",
                    "from": "+16503766005",
                    "body": "Zazo access code: 623030",
                    "status": "queued",
                    "num_segments": "1",
                    "num_media": "0",
                    "direction": "outbound-api",
                    "api_version": "2010-04-01",
                    "price": null,
                    "price_unit": "USD",
                    "error_code": null,
                    "error_message": null,
                    "uri": "/2010-04-01/Accounts/<twilio_ssid>/Messages/SM272eb583ba9f40859abd816e97958bbf.json",
                    "subresource_uris": {
                        "media": "/2010-04-01/Accounts/<twilio_ssid>/Messages/SM272eb583ba9f40859abd816e97958bbf/Media.json"
                    }
               }
            }
