source 'https://rubygems.org'

gem 'rails', '~> 4.2.3'
gem 'rails-api'
gem 'mysql2'
gem 'puma'
gem 'figaro', github: 'fny/figaro', branch: 'elastic-beanstalk-support'
gem 'pry-rails'
gem 'rollbar'
gem 'newrelic_rpm'
gem 'faraday'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'guard-pow', require: false
  gem 'terminal-notifier-guard'
  gem 'rb-fchange', require: false
  gem 'rb-fsevent', require: false
  gem 'rb-inotify', require: false
  gem 'rsense'
  gem 'spring'
end

group :development, :test do
  gem 'pry-rescue'
  gem 'pry-remote'
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'dredd-rack'
end

group :test do
  gem 'database_cleaner'
  gem 'capybara'
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'webmock'
  gem 'vcr'
  gem 'timecop'
end
