source 'https://rubygems.org'

gem 'rails', '~> 4.2.3'

gem 'awesome_print'
gem 'aws-sdk', '~> 2'
gem 'faraday'
gem 'faraday_middleware'
gem 'figaro', github: 'fny/figaro', branch: 'elastic-beanstalk-support'
gem 'newrelic_rpm'
gem 'pry-rails'
gem 'puma'
gem 'rails-api'
gem 'rollbar'
gem 'settingslogic'
gem 'twilio-ruby'

gem 'gcm'
gem 'houston'

group :development, :test do
  gem 'dredd-rack'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-byebug', '~> 1.3.3'
  gem 'pry-remote'
  gem 'pry-rescue'
  gem 'rspec-rails'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard-bundler'
  gem 'guard-pow', require: false
  gem 'guard-rails'
  gem 'guard-rake'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'rb-fchange', require: false
  gem 'rb-fsevent', require: false
  gem 'rb-inotify', require: false
  gem 'rsense'
  gem 'spring'
  gem 'terminal-notifier-guard'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'shoulda-matchers', require: false
  gem 'simplecov', require: false
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end
